POST http://localhost:3200/api/classroom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNjQyMzBmNGQ3YTU4YjY2Y2IyNjJlZSIsInR5cGVVc2VyIjoidGVhY2hlciIsImlhdCI6MTY2NzUwNzMyNX0.ACC1XpoidGoIq6N-4Q0O_Wa0DZxQCUTVyiRnEfbOUw8

{
    "asignature": "sociales",
    "curse": "1ro",
    "section": "A"
}