POST http://localhost:3200/api/teacher
Content-Type: application/json

{
    "name": "pablito02",
    "password": "pablito02",
    "email": "pablito02@gmail.com",
    "asignatures": ["lengua española"],
    "curses": ["1ro"]
}