POST http://localhost:3200/api/teacher
Content-Type: application/json

{
    "name": "juan",
    "password": "juan",
    "email": "juan@gmail.com",
    "asignature": "lengua española",
    "curses": ["3ro"]
}