PUT http://localhost:3200/api/teacher
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDNmYzg0YzYyNDg2ZGIwZTE2NzVlNSIsImlhdCI6MTY2MTIwNTk4Mn0.ozttpVLTJ11gd3wGAyQknnShOChmGwPSCQhAyU738ss

{
    "password": "jonas",
    "newPassword": "eljonas19"
}