DELETE http://localhost:3200/api/announcements
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNWRiZGZiMmU2ZTRlNjNhMmU0MDQ2YiIsInR5cGVVc2VyIjoidGVhY2hlciIsImlhdCI6MTY2NzA4Nzg4M30.kip7hri92snaruXdxMyStDbP2exa2-DDRiR4QR3Wuic

{
    "id": "635dbe492e6e4e63a2e40486"
}