PUT http://localhost:3200/student
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMDM4OTk5NmI4ZDZiMzVjNjQ3ZDI4MCIsImlhdCI6MTY2MTE3NjM5N30.5lqESQ5eggYVNKMZ__aedztVod3onDV_iNpYjSy9H-U

{
    "password": "darkenmax06",
    "newPassword": "enmanuelx06"
}